# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Mac Client

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 18-ea
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 18-ea
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: ./mvnw --no-transfer-progress install -Dinstaller=true
      - name: Upload PKG
        uses: actions/upload-artifact@v2
        with:
          name: PKG file
          path: target/installer/*.pkg